# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup PNPM
      uses: pnpm/action-setup@v1.2.0
      with:
        version: latest

    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/.pnpm-store/v3
        key: ${{ runner.os }}-pnpm

    - run: pnpm install

    - run: pnpm run build --if-present
    - run: pnpm test
      env:
        CI: true
